# Generated by Django 4.0.4 on 2022-04-26 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shortner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origna_url', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=10)),
            ],
        ),
    ]
