# Generated by Django 4.0.4 on 2022-04-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorted', '0002_alter_shortner_origna_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortner',
            name='key',
            field=models.CharField(help_text='Add something to append at last', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='shortner',
            name='origna_url',
            field=models.URLField(help_text='Add the original URL that you want to shorten.'),
        ),
    ]
